apiVersion: v1
kind: Service
metadata:
  name: cicd-project-service
  namespace: cicd
spec:
  type: NodePort
  selector:
    app: cicd-project
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000